default:
  seed: 42
  
  # logging savepath
  base_dir: tb_logs
  name: spin
  version: default

  # model
  solver:
    rtol: 1.e-3
    atol: 1.e-4
    max_steps: 8192

  # training
  epochs: 100
  learning_rate: 1.e-3
  ckpt_keep: 10
  ckpt_interval: 1000