default: &default
  seed: 0

  scheme: toy

  obs_num: 1
  obs_sample: 4
  obs_noise: null
  obs_noise_rep: 1

  # model
  solver:
    rtol: 1.e-6
    atol: 1.e-7
    max_steps: 100000
    checkpoints: 10000
  
  ckpt_keep: 3
  # resume from `save_dir` if `resume` is True and `resume_ckpt` is null
  resume_ckpt: null

traj_fit:
  <<: *default
  epochs: 2000
  learning_rate: 1.e-2
  test_interval: 50
  ckpt_interval: 10

est_rate_dydt: &est_rate_dydt
  <<: *default
  obs_num: 1
  obs_sample: 50

  k_noise: 1.e-1

est_rate_neural_ode:
  <<: *est_rate_dydt
  dydt: "neural_ode"
  neural_ode_ckpt: experiments/traj_fit/test/checkpoints

  epochs: 5000
  learning_rate: 1.e-2
  test_interval: 200
  ckpt_interval: 10

est_rate_finite_diff:
  <<: *est_rate_dydt
  dydt: "finite_diff"

  steps: 2000
  batch_size: 1
  learning_rate: 1.e-3
  test_interval: 500
  ckpt_interval: 500

est_rate_traj:
  <<: *default
  obs_num: 10
  
  k_noise: 1.e-1

  steps: 2000
  batch_size: 1
  learning_rate: 1.e-3
  test_interval: 50
  ckpt_interval: 10
